# Generated by Django 3.0.1 on 2019-12-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191220_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='secret_code',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='secret_code',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
