# Generated by Django 3.0.1 on 2019-12-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20191220_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetgroup',
            name='external_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Country'),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.TargetGroup'),
        ),
    ]
